### ISSUE TITLE
Error GA_TOKEN is not defined

### ISSUE THREAD

**Issue by cafe4it** [YounGoat/gitbook-plugin-analytics#1]
Hi, i installed & config : 
```
"analytics": [
{
"vendor": "google",
"token": "UA-XXXXXX-YY",
"base": "https://www.dropshipwith.me"
}
]
```

**Comment by YounGoat** [comment]
I will release a new version today or tomorrow, trying to solve your problem.
BTW, what is the version of your gitbook? Run ``gitbook versions``` or see "gitbook" in your book.json.

**Comment by YounGoat** [comment]
@cafe4it New version has been released, please try again.
