### ISSUE TITLE
Error with plugin "analytics": Cannot find module 'colors'

### ISSUE THREAD

**Issue by oscarpalomar** [YounGoat/gitbook-plugin-analytics#2]
Error installing component on gitbook.

This is the error ...

info: loading plugin "analytics"... ERROR

PluginError: Error with plugin "analytics": Cannot find module 'colors'

**Comment by YounGoat** [comment]
@oscarpalomar thanks for your remind. I forgot to add dependencies before commit. The bug has been fixed and new version 0.1.1 published already. And, I also unpublished the incorrect version 0.1.0.

**Comment by YounGoat** [comment]
@oscarpalomar is it ok now?

**Comment by oscarpalomar** [comment]
Yes. Now works fine. Thank you very much.
